import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame} from 'remotion';

const paper='#f1eee6', ink='#14272b', teal='#2a6f7a', orange='#f17242';
const ease={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
const ramp=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],ease);
const enter=(f:number,delay=0)=>spring({frame:f-delay,fps:30,config:{damping:22,stiffness:115,mass:0.9}});
const serif='Georgia, serif';
const Face=({size=54}:{size?:number})=><svg width={size} height={size} viewBox="0 0 44 44"><circle cx="22" cy="22" r="20" fill={teal} stroke={ink} strokeWidth="2"/><circle cx="15" cy="16" r="2" fill="white"/><circle cx="29" cy="16" r="2" fill="white"/><path d="M16 28 Q22 34 28 28" fill="none" stroke="white" strokeWidth="2.2" strokeLinecap="round"/></svg>;
const Label=({children}:{children:React.ReactNode})=><div style={{fontSize:20,letterSpacing:4,textTransform:'uppercase',fontWeight:600}}>{children}</div>;
const Reveal=({children,delay=0,style={}}:{children:React.ReactNode;delay?:number;style?:React.CSSProperties})=>{const f=useCurrentFrame();const p=enter(f,delay);return <div style={{opacity:ramp(f,delay,delay+10),transform:`translateY(${(1-p)*65}px)`,...style}}>{children}</div>};
const Brand=()=> <div style={{display:'flex',alignItems:'center',gap:14,fontWeight:650,fontSize:26}}><Face size={42}/>HireAlpha</div>;
const Background=({dark=false}:{dark?:boolean})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:dark?ink:paper,overflow:'hidden'}}><div style={{position:'absolute',width:1100,height:1100,left:1100,top:-570,borderRadius:'50%',background:dark?'#36727a':'#d4e2df',filter:'blur(100px)',opacity:0.45,transform:`translateX(${Math.sin(f/130)*80}px)`}}/><div style={{position:'absolute',width:650,height:650,left:-300,top:700,borderRadius:'50%',background:dark?'#896450':'#e9c9af',filter:'blur(100px)',opacity:.28}}/></AbsoluteFill>};
const Shell=({children,dark=false}:{children:React.ReactNode;dark?:boolean})=><AbsoluteFill style={{color:dark?paper:ink}}><Background dark={dark}/><div style={{position:'absolute',left:92,top:60}}><Brand/></div>{children}</AbsoluteFill>;

function Opening(){const f=useCurrentFrame();const words=['The meeting.','The inbox.','The meal.','The follow-up.'];return <Shell><div style={{position:'absolute',left:120,top:250,zIndex:2}}><Reveal><Label>Life is a full-time job.</Label></Reveal><Reveal delay={5}><div style={{fontFamily:serif,fontSize:132,letterSpacing:-7,lineHeight:1.04,marginTop:30}}>Your day has<br/>too many <span style={{fontStyle:'italic',color:teal}}>tabs.</span></div></Reveal></div><div style={{position:'absolute',left:1180,top:195,perspective:1300}}>{words.map((w,i)=>{const p=enter(f,i*7);return <div key={w} style={{position:'absolute',top:i*148,left:i%2?45:0,width:500,padding:'32px 36px',fontSize:38,border:'1px solid #b5c4c1',borderRadius:20,background:'#faf9f4',boxShadow:'0 22px 45px #183d3312',transform:`translateY(${(1-p)*110}px) rotate(${(i%2?3:-3)+Math.sin(f/35+i)*.5}deg)`,opacity:p}}><span style={{color:orange,marginRight:22}}>↗</span>{w}</div>})}</div><div style={{position:'absolute',left:120,bottom:100,fontSize:25,color:'#677571'}}>Meet the assistant already in your Messages.</div></Shell>}

function Phone({children,style={}}:{children:React.ReactNode;style?:React.CSSProperties}){return <div style={{width:520,height:910,borderRadius:65,background:'#24282a',padding:10,boxShadow:'0 55px 100px #071b2830, inset 0 0 0 2px #89918f',...style}}><div style={{height:'100%',borderRadius:55,background:'#fff',overflow:'hidden',position:'relative',color:'#111'}}><div style={{height:55,padding:'18px 28px',fontSize:19,fontWeight:650,display:'flex',justifyContent:'space-between'}}><span>9:41</span><span>▮▮▮  ▰</span></div><div style={{position:'absolute',top:13,left:165,width:190,height:35,borderRadius:28,background:'#090c0d'}}/><div style={{display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',paddingBottom:17,borderBottom:'1px solid #ededed'}}><Face size={64}/><span style={{fontSize:20,marginTop:5}}>Alpha ›</span></div>{children}<div style={{position:'absolute',bottom:26,left:28,right:28,display:'flex',gap:14,alignItems:'center',color:'#999',fontSize:26}}><span>＋</span><div style={{border:'1px solid #ddd',borderRadius:25,padding:'9px 18px',fontSize:18,flex:1}}>iMessage</div></div><div style={{position:'absolute',bottom:9,left:174,width:170,height:5,borderRadius:6,background:'#111'}}/></div></div>}
function Bubble({children,out=false,delay=0}:{children:React.ReactNode;out?:boolean;delay?:number}){return <Reveal delay={delay} style={{alignSelf:out?'flex-end':'flex-start',maxWidth:'92%'}}><div style={{background:out?'#2582ed':'#ececee',color:out?'white':'#141414',borderRadius:25,padding:'17px 21px',fontSize:25,lineHeight:1.35}}>{children}</div></Reveal>}
function TextFirst(){const f=useCurrentFrame();return <Shell><div style={{position:'absolute',left:125,top:305,width:880}}><Reveal><Label>01 / A head start</Label></Reveal><Reveal delay={4}><div style={{fontFamily:serif,fontSize:117,letterSpacing:-5,lineHeight:1.04,marginTop:30}}>An assistant<br/>who texts <i style={{color:teal}}>first.</i></div></Reveal><Reveal delay={16}><p style={{fontSize:31,lineHeight:1.5,color:'#64716e',maxWidth:720}}>Your day, pulled together.<br/>Before you have to ask.</p></Reveal></div><div style={{position:'absolute',left:1190,top:130,transform:`translateY(${(1-enter(f))*160}px) rotate(${interpolate(f,[0,150],[5,-2],ease)}deg) scale(0.94)`}}><Phone><div style={{padding:'20px 25px',display:'flex',flexDirection:'column',gap:20}}><div style={{fontSize:16,textAlign:'center',color:'#98989d'}}>Today 8:00 AM</div><Bubble delay={14}>Morning. Your first meeting is at 10. Your brief is ready.</Bubble><Reveal delay={40}><div style={{border:'1px solid #d7e2dd',borderRadius:24,overflow:'hidden',background:'#eff5f0'}}><div style={{padding:25}}><Label>Morning brief</Label><div style={{fontFamily:serif,fontSize:38,marginTop:18}}>A clearer day.</div><div style={{fontSize:21,marginTop:15,color:'#62746e'}}>Calendar · Priorities · Open loops</div></div><div style={{background:'#ddece4',padding:'16px 25px',fontSize:22,color:teal}}>Open your brief ↗</div></div></Reveal><Bubble delay={86} out>Exactly what I needed.</Bubble></div></Phone></div><div style={{position:'absolute',bottom:45,right:100,fontSize:16,color:'#687875'}}>Illustrative conversation</div></Shell>}
function Brief(){const f=useCurrentFrame();return <Shell dark><div style={{position:'absolute',left:120,top:250,width:630}}><Reveal><Label>02 / See what matters</Label></Reveal><Reveal delay={5}><div style={{fontFamily:serif,fontSize:108,lineHeight:1.06,letterSpacing:-4,marginTop:35}}>Less noise.<br/><i style={{color:'#a7d7c8'}}>More clarity.</i></div></Reveal><Reveal delay={18}><p style={{fontSize:29,lineHeight:1.5,color:'#b0c3bd'}}>Your calendar, priorities, and<br/>unfinished business. Together.</p></Reveal></div><div style={{position:'absolute',left:900,top:155,width:850,transform:`perspective(1800px) rotateY(${interpolate(f,[0,150],[-9,-2],ease)}deg) translateY(${(1-enter(f))*100}px)`,background:'#152e30',border:'1px solid #43605b',borderRadius:32,padding:48,boxShadow:'0 45px 100px #0005'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:18,color:'#a7c4b7',letterSpacing:3}}><span>ALPHA / MORNING BRIEF</span><span>08:00</span></div><div style={{fontSize:57,letterSpacing:-2,marginTop:35,fontWeight:550}}>Good morning.</div><p style={{fontSize:24,color:'#adc0b9'}}>A little room to breathe.</p>{[['10:00','Design review','Your first meeting'],['NEXT','Prepare launch notes','One thing to move forward'],['OPEN LOOP','Reply to Sam','Keep the conversation moving']].map(([time,title,sub],i)=><Reveal key={time} delay={20+i*17}><div style={{padding:'25px 0',borderTop:'1px solid #35504b',display:'flex',alignItems:'center',gap:28}}><div style={{width:128,color:'#b0dccc',fontSize:17,letterSpacing:1}}>{time}</div><div><div style={{fontSize:29}}>{title}</div><div style={{fontSize:19,color:'#91aaa1',marginTop:8}}>{sub}</div></div><span style={{marginLeft:'auto',color:'#b0dccc',fontSize:28}}>↗</span></div></Reveal>)}</div><div style={{position:'absolute',bottom:45,right:100,fontSize:16,color:'#adc0b9'}}>Illustrative brief · Sample data</div></Shell>}
function Meal(){const f=useCurrentFrame();return <Shell><div style={{position:'absolute',left:115,top:235,width:990}}><Reveal><Label>03 / Just text it</Label></Reveal><Reveal delay={5}><div style={{fontFamily:serif,fontSize:112,letterSpacing:-5,lineHeight:1.05,marginTop:35}}>Small message.<br/><i style={{color:teal}}>Real momentum.</i></div></Reveal><Reveal delay={20}><p style={{fontSize:30,lineHeight:1.5,color:'#64716e'}}>Food. Habits. Workouts.<br/>Keep moving, right from your conversation.</p></Reveal></div><div style={{position:'absolute',left:1170,top:118,transform:`scale(.96) rotate(${interpolate(f,[0,150],[3,-1],ease)}deg)`}}><Phone><div style={{padding:25,display:'flex',flexDirection:'column',gap:20}}><Bubble out delay={5}>Chicken bowl with guac.</Bubble><Bubble delay={30}>Logged. Here’s your nutrition estimate.</Bubble><Reveal delay={53}><div style={{background:'#172c2b',borderRadius:24,color:paper,padding:26}}><div style={{fontSize:17,letterSpacing:2,color:'#afd5c7'}}>NUTRITION / TODAY</div><div style={{display:'flex',alignItems:'baseline',gap:12,marginTop:25}}><span style={{fontSize:68,letterSpacing:-3}}>{Math.round(820*ramp(f,53,76))}</span><span style={{fontSize:22,color:'#b4c4bf'}}>kcal</span></div><div style={{height:6,background:'#40544e',borderRadius:4,margin:'20px 0'}}><div style={{height:6,width:`${ramp(f,58,85)*66}%`,background:'#b9e4cf',borderRadius:4}}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:23}}><span>Protein</span><strong>54g</strong></div><div style={{fontSize:16,color:'#b4c4bf',marginTop:25}}>AI estimate · Adjust anytime</div></div></Reveal></div></Phone></div><div style={{position:'absolute',bottom:45,right:100,fontSize:16,color:'#687875'}}>Illustrative conversation · Sample data</div></Shell>}
function Payoff(){const f=useCurrentFrame();return <Shell dark><div style={{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',textAlign:'center'}}><Reveal><div style={{fontSize:30,color:'#a9c5bc',marginBottom:30}}>A little less managing.</div></Reveal><Reveal delay={9}><div style={{fontFamily:serif,fontSize:150,letterSpacing:-6,lineHeight:1.03}}>A little more<br/><i style={{color:'#b8e1cf'}}>living.</i></div></Reveal><div style={{width:interpolate(f,[20,65],[0,320],ease),height:2,background:'#b8e1cf',marginTop:50}}/></div></Shell>}
function End(){const f=useCurrentFrame();return <Shell><div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',transform:`scale(${interpolate(f,[0,119],[.97,1.015],ease)})`}}><Reveal><Face size={120}/></Reveal><Reveal delay={5}><div style={{fontFamily:serif,fontSize:145,letterSpacing:-8,marginTop:20}}>HireAlpha</div></Reveal><Reveal delay={12}><div style={{fontSize:35,marginTop:20,color:'#5c706b'}}>Your personal assistant. In Messages.</div></Reveal><Reveal delay={20}><div style={{marginTop:50,background:ink,color:paper,borderRadius:60,padding:'23px 48px',fontSize:34}}>Meet Alpha <span style={{margin:'0 15px',color:'#b0dccc'}}>↗</span> hirealpha.chat</div></Reveal></div></Shell>}
export const LaunchFilm=()=> <AbsoluteFill style={{fontFamily:'Inter, sans-serif',background:paper}}><style>{`@font-face{font-family:Inter;src:url('${staticFile('inter.woff2')}') format('woff2');font-weight:100 900}*{box-sizing:border-box}`}</style><Audio src={staticFile('launch-score.wav')}/><Sequence durationInFrames={120}><Opening/></Sequence><Sequence from={120} durationInFrames={165}><TextFirst/></Sequence><Sequence from={285} durationInFrames={165}><Brief/></Sequence><Sequence from={450} durationInFrames={180}><Meal/></Sequence><Sequence from={630} durationInFrames={150}><Payoff/></Sequence><Sequence from={780} durationInFrames={120}><End/></Sequence></AbsoluteFill>;
