import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame} from 'remotion';

const clamp = {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const;
const progress = (f: number, a: number, b: number) => interpolate(f, [a,b], [0,1], clamp);
const motion = (f: number, delay = 0) => spring({frame:f-delay,fps:30,config:{damping:24,stiffness:150}});
const mint = '#b9f7da';
function Mark({size=52, dark=false}:{size?:number;dark?:boolean}) {
  return <svg width={size} height={size} viewBox="0 0 50 50"><circle cx="25" cy="25" r="23" fill={dark?mint:'#2a6f7a'}/><g fill={dark?'#102921':'white'}><circle cx="17" cy="19" r="2.3"/><circle cx="33" cy="19" r="2.3"/></g><path d="M17 31 Q25 39 33 31" fill="none" stroke={dark?'#102921':'white'} strokeWidth="2.5" strokeLinecap="round"/></svg>;
}
function In({children,delay=0,style={}}:{children:React.ReactNode;delay?:number;style?:React.CSSProperties}) {
  const f=useCurrentFrame(), p=motion(f,delay);
  return <div style={{opacity:progress(f,delay,delay+8),transform:`translateY(${(1-p)*75}px)`,...style}}>{children}</div>;
}
function Frame({children,dark=false}:{children:React.ReactNode;dark?:boolean}) {
  const f=useCurrentFrame();
  return <AbsoluteFill style={{background:dark?'#080d10':'#f6f2e9',color:dark?'#f5f7f2':'#163633',overflow:'hidden'}}>
    {dark && <><div style={{position:'absolute',width:1100,height:700,left:500,top:280,borderRadius:'50%',background:'radial-gradient(ellipse,#245b5055,transparent 70%)',transform:`translateX(${Math.sin(f/100)*90}px)`}}/><div style={{position:'absolute',inset:0,opacity:.1,backgroundImage:'linear-gradient(#8ecdb622 1px,transparent 1px),linear-gradient(90deg,#8ecdb622 1px,transparent 1px)',backgroundSize:'80px 80px'}}/></>}
    <div style={{position:'absolute',left:72,top:48,display:'flex',alignItems:'center',gap:12,fontSize:27,fontWeight:650,zIndex:5}}><Mark dark={dark} size={40}/>HireAlpha</div>
    {children}
  </AbsoluteFill>;
}
function Small({children}:{children:React.ReactNode}) {return <div style={{fontSize:21,letterSpacing:4,fontWeight:600,textTransform:'uppercase'}}>{children}</div>}
function Center({children}:{children:React.ReactNode}) {return <div style={{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',textAlign:'center'}}>{children}</div>}
function DemoNote({dark=false}:{dark?:boolean}) {return <div style={{position:'absolute',bottom:30,right:60,fontSize:17,color:dark?'#91b1a7':'#687e75'}}>Illustrative demo · Sample data</div>}

function TrailerHook(){const f=useCurrentFrame();return <Frame dark><Center><div style={{fontSize:29,color:mint,letterSpacing:5,marginBottom:38}}>THE DAY STARTS.</div><div style={{fontSize:154,fontWeight:760,lineHeight:1.03,letterSpacing:-9}}>So does<br/><span style={{color:mint}}>everything else.</span></div></Center>{['MEETING AT 10','LOG LUNCH','FOLLOW UP','PLAN TOMORROW'].map((t,i)=><div key={t} style={{position:'absolute',left:[95,1450,120,1380][i],top:[230,245,815,815][i],padding:'19px 25px',border:'1px solid #64887c',background:'#12211e',borderRadius:16,fontSize:21,color:'#cfdfd6',transform:`translateY(${(1-motion(f,i*5))*180}px) rotate(${[-9,7,5,-6][i]}deg)`,opacity:progress(f,i*5,i*5+10)}}>{t}</div>)}</Frame>}
function TrailerReveal(){const f=useCurrentFrame();return <Frame dark><Center><In><div style={{transform:`scale(${1+progress(f,0,105)*.08})`,marginBottom:30}}><Mark size={150} dark/></div></In><In delay={6}><div style={{fontSize:140,fontWeight:700,letterSpacing:-7}}>Meet your <span style={{color:mint}}>Alpha.</span></div></In><In delay={20}><div style={{fontSize:38,color:'#adcbc0',marginTop:35}}>A personal assistant. Already in Messages.</div></In></Center></Frame>}
function TrailerBrief(){const f=useCurrentFrame();return <Frame dark><div style={{position:'absolute',left:105,top:260,width:650}}><In><Small>01 / Before you ask</Small></In><In delay={5}><div style={{fontSize:103,fontWeight:700,letterSpacing:-5,lineHeight:1.05,marginTop:35}}>Your day.<br/><span style={{color:mint}}>In focus.</span></div></In><In delay={17}><div style={{fontSize:29,color:'#b6cec4',lineHeight:1.5,marginTop:30}}>Alpha texts first.<br/>Your morning brief is ready.</div></In></div><div style={{position:'absolute',left:860,top:150,width:920,transform:`perspective(1600px) rotateY(${interpolate(f,[0,170],[-8,0],clamp)}deg) translateY(${(1-motion(f))*100}px)`}}><div style={{padding:35,background:'#1b2b27',border:'1px solid #4d7767',borderRadius:28,boxShadow:'0 40px 90px #0008'}}><div style={{display:'flex',alignItems:'center',gap:20}}><Mark dark/><div style={{fontSize:25}}>Alpha <span style={{color:'#88a99a',fontSize:20,marginLeft:370}}>now</span></div></div><div style={{fontSize:35,lineHeight:1.3,marginTop:22}}>Your first meeting is at 10.<br/>Here’s what needs your attention.</div></div><In delay={30}><div style={{background:'#e1f2e8',color:'#15392b',padding:38,borderRadius:28,marginTop:24}}><Small>Morning brief</Small>{[['10:00','Design review'],['PRIORITY','Prepare launch notes'],['OPEN LOOP','Reply to Sam']].map(([a,b],i)=><In key={a} delay={40+i*14}><div style={{display:'flex',gap:40,padding:'23px 0',borderBottom:'1px solid #bbd6c7',alignItems:'center'}}><span style={{width:155,fontSize:19,color:'#4d7767'}}>{a}</span><span style={{fontSize:31,fontWeight:550}}>{b}</span></div></In>)}</div></In></div><DemoNote dark/></Frame>}
function TrailerMeal(){const f=useCurrentFrame();return <Frame dark><div style={{position:'absolute',left:105,top:245}}><In><Small>02 / Keep it simple</Small></In><In delay={4}><div style={{fontSize:103,fontWeight:700,letterSpacing:-5,lineHeight:1.05,marginTop:35}}>You text.<br/><span style={{color:mint}}>Alpha logs.</span></div></In><In delay={20}><div style={{fontSize:29,color:'#b6cec4',marginTop:35}}>Less tracking. More momentum.</div></In></div><div style={{position:'absolute',left:930,top:180,width:800}}><In><div style={{background:'#217be8',fontSize:37,padding:'28px 36px',borderRadius:'32px 32px 8px 32px',marginLeft:60}}>Chicken bowl with guac.</div></In><In delay={28}><div style={{marginTop:35,border:'1px solid #436e5d',background:'#152a22',padding:42,borderRadius:28}}><Small>Nutrition / logged</Small><div style={{fontSize:126,letterSpacing:-7,color:mint,marginTop:18}}>{Math.round(820*progress(f,30,60))}<span style={{fontSize:31,letterSpacing:0,color:'#adc6b7'}}> kcal</span></div><div style={{height:8,background:'#385143',borderRadius:8,margin:'25px 0'}}><div style={{height:8,background:mint,width:`${progress(f,35,70)*70}%`,borderRadius:8}}/></div><div style={{fontSize:32,display:'flex',justifyContent:'space-between'}}><span>Protein</span><strong>54g</strong></div><div style={{fontSize:20,color:'#a9c4b5',marginTop:35}}>AI estimate · Adjust anytime</div></div></In></div><DemoNote dark/></Frame>}
function TrailerPayoff(){return <Frame dark><Center><In><Small>Make room for your life.</Small></In><In delay={7}><div style={{fontSize:150,fontWeight:720,letterSpacing:-8,lineHeight:1.02,marginTop:40}}>Less to manage.<br/><span style={{color:mint}}>More to live.</span></div></In></Center></Frame>}
function TrailerEnd(){return <Frame dark><Center><In><Mark size={110} dark/></In><In delay={5}><div style={{fontSize:153,fontWeight:700,letterSpacing:-8,marginTop:25}}>HireAlpha</div></In><In delay={13}><div style={{fontSize:34,color:'#b7cfc4',marginTop:20}}>Your personal assistant in Messages.</div></In><In delay={21}><div style={{fontSize:39,background:mint,color:'#133529',borderRadius:60,padding:'23px 46px',marginTop:45}}>hirealpha.chat ↗</div></In></Center></Frame>}

function ChatHeader(){return <div style={{position:'absolute',left:70,right:70,top:150,paddingBottom:30,borderBottom:'2px solid #d8dfd4',display:'flex',alignItems:'center',gap:25}}><Mark size={74}/><div><div style={{fontSize:40,fontWeight:650}}>Alpha</div><div style={{fontSize:22,color:'#617d70'}}>Your personal assistant</div></div><div style={{marginLeft:'auto',fontSize:40}}>↗</div></div>}
function ChatBubble({children,out=false,delay=0}:{children:React.ReactNode;out?:boolean;delay?:number}){return <In delay={delay} style={{alignSelf:out?'flex-end':'flex-start',maxWidth:830}}><div style={{fontSize:42,lineHeight:1.3,background:out?'#287eed':'#e4e8df',color:out?'white':'#163633',padding:'28px 35px',borderRadius:out?'35px 35px 8px 35px':'35px 35px 35px 8px'}}>{children}</div></In>}
function ChatHook(){return <Frame><Center><div style={{fontSize:30,letterSpacing:3,color:'#667c6c',marginBottom:35}}>ONE CONTACT.</div><In><div style={{fontFamily:'Georgia,serif',fontSize:124,lineHeight:1.02,letterSpacing:-6}}>A little less<br/><i>on your mind.</i></div></In><In delay={18}><div style={{background:'#2a6f7a',color:'white',padding:'22px 35px',borderRadius:45,fontSize:32,marginTop:50}}>Meet Alpha ↗</div></In></Center></Frame>}
function ChatMorning(){return <Frame><ChatHeader/><div style={{position:'absolute',left:70,right:70,top:295,display:'flex',flexDirection:'column',gap:25}}><div style={{textAlign:'center',fontSize:21,color:'#708271'}}>Today 8:00 AM</div><ChatBubble delay={6}>Morning. Your first meeting is at 10. Your brief is ready.</ChatBubble><In delay={33}><div style={{background:'#173f37',color:'#f5f2e9',borderRadius:26,padding:35,width:780}}><Small>Morning brief</Small><div style={{fontFamily:'Georgia,serif',fontSize:62,marginTop:20}}>A clearer day.</div><div style={{fontSize:29,marginTop:20,color:'#c4dacb'}}>Calendar · Priorities · Open loops</div><div style={{fontSize:29,marginTop:30,color:mint}}>Open your brief ↗</div></div></In></div><DemoNote/></Frame>}
function ChatMeal(){return <Frame><ChatHeader/><div style={{position:'absolute',left:70,right:70,top:295,display:'flex',flexDirection:'column',gap:25}}><ChatBubble out delay={4}>Chicken bowl with guac.</ChatBubble><ChatBubble delay={28}>Logged. Here’s your estimate.</ChatBubble><In delay={48}><div style={{border:'2px solid #acc9b8',borderRadius:30,padding:35,width:780,background:'#e3eee2'}}><Small>Nutrition / today</Small><div style={{display:'flex',gap:65,marginTop:26}}><div><strong style={{fontSize:81,letterSpacing:-4}}>820</strong><div style={{fontSize:26}}>kcal</div></div><div><strong style={{fontSize:81,letterSpacing:-4}}>54g</strong><div style={{fontSize:26}}>protein</div></div></div><div style={{fontSize:21,color:'#607967',marginTop:25}}>AI estimate · Adjust anytime</div></div></In></div><DemoNote/></Frame>}
function ChatLife(){const f=useCurrentFrame();const items=['Your morning.','Your meals.','Your habits.'];return <Frame><div style={{position:'absolute',left:85,top:265}}><Small>All from a conversation.</Small>{items.map((t,i)=><In key={t} delay={i*17}><div style={{fontFamily:'Georgia,serif',fontSize:105,letterSpacing:-4,marginTop:35,color:i===2?'#2a6f7a':'#163633'}}>{t}<span style={{fontSize:60,marginLeft:30,opacity:progress(f,i*17+10,i*17+20)}}>↗</span></div></In>)}</div></Frame>}
function ChatEnd(){return <Frame><Center><In><Mark size={125}/></In><In delay={5}><div style={{fontFamily:'Georgia,serif',fontSize:123,letterSpacing:-6,marginTop:30}}>HireAlpha</div></In><In delay={13}><div style={{fontSize:36,lineHeight:1.45,marginTop:25}}>A personal assistant.<br/>Right in your Messages.</div></In><In delay={20}><div style={{background:'#173f37',color:'#f6f2e9',padding:'25px 44px',borderRadius:60,fontSize:39,marginTop:45}}>hirealpha.chat ↗</div></In></Center></Frame>}
function Font(){return <style>{`@font-face{font-family:Inter;src:url('${staticFile('inter.woff2')}') format('woff2');font-weight:100 900}*{box-sizing:border-box}`}</style>}
export function MidnightFilm(){return <AbsoluteFill style={{fontFamily:'Inter,sans-serif'}}><Font/><Audio src={staticFile('midnight-score.wav')}/><Sequence durationInFrames={105}><TrailerHook/></Sequence><Sequence from={105} durationInFrames={105}><TrailerReveal/></Sequence><Sequence from={210} durationInFrames={180}><TrailerBrief/></Sequence><Sequence from={390} durationInFrames={180}><TrailerMeal/></Sequence><Sequence from={570} durationInFrames={180}><TrailerPayoff/></Sequence><Sequence from={750} durationInFrames={150}><TrailerEnd/></Sequence></AbsoluteFill>}
export function ConversationFilm(){return <AbsoluteFill style={{fontFamily:'Inter,sans-serif'}}><Font/><Audio src={staticFile('conversation-score.wav')}/><Sequence durationInFrames={120}><ChatHook/></Sequence><Sequence from={120} durationInFrames={210}><ChatMorning/></Sequence><Sequence from={330} durationInFrames={210}><ChatMeal/></Sequence><Sequence from={540} durationInFrames={180}><ChatLife/></Sequence><Sequence from={720} durationInFrames={180}><ChatEnd/></Sequence></AbsoluteFill>}
