/** Self hosted demos in public/workout. GIFs from ExerciseDB where the lift matched. Photos from free-exercise-db otherwise. */
export const EXERCISE_DEMO_MAP: Record<string, string> = {
  'push ups': '/workout/push-ups.jpg',
  'pike push ups': '/workout/pike-to-cobra.gif',
  'diamond push ups': '/workout/diamond-push-ups.gif',
  'wide push ups': '/workout/wide-push-ups.jpg',
  'hindu push ups': '/workout/hindu-push-ups.gif',
  'decline push ups': '/workout/decline-push-ups.gif',
  'superman': '/workout/superman.jpg',
  'glute kickback': '/workout/glute-kickback.jpg',
  'cobra': '/workout/cobra.gif',
  'back extension': '/workout/back-extension.jpg',
  'glute bridge': '/workout/glute-bridge.gif',
  'plank': '/workout/plank.jpg',
  'squat': '/workout/squat.jpg',
  'reverse lunge': '/workout/reverse-lunge.jpg',
  'jump squat': '/workout/jump-squat.gif',
  'calf raise': '/workout/standing-calf-raise.gif',
  'split squat': '/workout/split-squat.gif',
  'single leg glute bridge': '/workout/single-leg-glute-bridge.gif',
  'walking lunge': '/workout/walking-lunge.gif',
  'bench press': '/workout/bench-press.gif',
  'overhead press': '/workout/overhead-press.gif',
  'incline dumbbell press': '/workout/incline-dumbbell-press.gif',
  'tricep pushdown': '/workout/tricep-pushdown.gif',
  'lateral raise': '/workout/lateral-raise.gif',
  'cable fly': '/workout/cable-fly.gif',
  'barbell row': '/workout/barbell-row.gif',
  'lat pulldown': '/workout/lat-pulldown.gif',
  'seated cable row': '/workout/seated-cable-row.gif',
  'dumbbell curl': '/workout/dumbbell-curl.gif',
  'face pull': '/workout/face-pull.jpg',
  'hammer curl': '/workout/hammer-curl.gif',
  'back squat': '/workout/barbell-squat.gif',
  'romanian deadlift': '/workout/romanian-deadlift.gif',
  'leg press': '/workout/leg-press.jpg',
  'leg extension': '/workout/leg-extension.gif',
  'hanging knee raise': '/workout/hanging-knee-raise.jpg',
  'incline bench': '/workout/incline-bench.gif',
  'pull ups': '/workout/pull-ups.jpg',
  'seated dumbbell press': '/workout/seated-dumbbell-press.gif',
  'chest supported row': '/workout/chest-supported-row.gif',
  'deadlift': '/workout/deadlift.gif',
  'bulgarian split squat': '/workout/split-squat.gif',
  'leg curl': '/workout/leg-curl.gif',
  'hip abductor': '/workout/hip-abductor.jpg',
}

export function exerciseDemoUrl(name: string): string | null {
  return EXERCISE_DEMO_MAP[name.toLowerCase().trim()] ?? null
}
